# Generated by Django 4.0.5 on 2022-06-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bngjobs',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
